name: MacOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
     
  macos_6_7_2_build_cmake:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: jurplel/install-qt-action@v4
      with:
        # Directory to install Qt
        dir: # optional
        # Version of Qt to install
        version: '6.7.2'
        # Host platform
        host: 'mac'
        # Target platform for build
        target: 'desktop'
        # Architecture for Windows/Android
        arch: # optional
        # Whether or not to install Qt dependencies on Linux
        install-deps: 'true'
        # Additional Qt modules to install
        modules: #'qtscript qtscripttools'
        # Force a Qt mirror in case the default is not working
        #mirror: # optional
        # Whether or not to actually download Qt
        cached: # optional, default is false
        # Version of aqtinstall to use in case of issues
        aqtversion: # optional, default is ==0.8
        # Version of py7zr to use in case of issues
        py7zrversion: # optional, default is ==0.6
        # Any extra arguments to append to the back
        extra: # optional
    - name: Install Qt and compile
      run: |
        mkdir build
        ls -lrt
        cmake -S . -B ./build
        ls -lrt
        cd ./build
        ls -lrt
        make
        ls -lrt

        which macdeployqt
        macdeployqt pico.app -dmg -qmldir=. -verbose=2
        ls -lrt

  macos_6_7_2_build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: jurplel/install-qt-action@v4
      with:
        # Directory to install Qt
        dir: # optional
        # Version of Qt to install
        version: '6.7.2'
        # Host platform
        host: 'mac'
        # Target platform for build
        target: 'desktop'
        # Architecture for Windows/Android
        arch: # optional
        # Whether or not to install Qt dependencies on Linux
        install-deps: 'true'
        # Additional Qt modules to install
        modules: #'qtscript qtscripttools'
        # Force a Qt mirror in case the default is not working
        #mirror: # optional
        # Whether or not to actually download Qt
        cached: # optional, default is false
        # Version of aqtinstall to use in case of issues
        aqtversion: # optional, default is ==0.8
        # Version of py7zr to use in case of issues
        py7zrversion: # optional, default is ==0.6
        # Any extra arguments to append to the back
        extra: # optional
    - name: Install Qt and compile
      run: |
        qmake -r pico.pro
        ls -lrt
        make
        ls -lrt

        which macdeployqt
        macdeployqt pico.app -dmg -qmldir=. -verbose=2
        ls -lrt

  macos_5_15_2_build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: jurplel/install-qt-action@v4
      with:
        # Directory to install Qt
        dir: # optional
        # Version of Qt to install
        version: '5.15.2'
        # Host platform
        host: 'mac'
        # Target platform for build
        target: 'desktop'
        # Architecture for Windows/Android
        arch: # optional
        # Whether or not to install Qt dependencies on Linux
        install-deps: 'true'
        # Additional Qt modules to install
        modules: #'qtscript qtscripttools'
        # Force a Qt mirror in case the default is not working
        #mirror: # optional
        # Whether or not to actually download Qt
        cached: # optional, default is false
        # Version of aqtinstall to use in case of issues
        aqtversion: # optional, default is ==0.8
        # Version of py7zr to use in case of issues
        py7zrversion: # optional, default is ==0.6
        # Any extra arguments to append to the back
        extra: # optional
    - name: Install Qt and compile
      run: |
        qmake -r pico.pro
        ls -lrt
        make
        ls -lrt

        which macdeployqt
        macdeployqt pico.app -dmg -qmldir=. -verbose=2
        ls -lrt

